### ISSUE TITLE
UNO: Rangos

### ISSUE THREAD

**Issue by Darukia** [Slayer95/Pandora-Showdown#10]
Otra idea que tuve trata básicamente sobre los Rangos de la sala "UNO Tower" que se obtengan mediante la actividad del usuario en ya dicha sala, sus partidas ganadas, y sus "Logros".(Tema anterior)
Para las partidas ganadas se utilizaría una especie de "Tourhof" (Cantidad de partidas ganadas).
Ejemplo:
-Destacado: 25 Partidas Ganadas, Actividad reciente en la sala, Logros (Carta 9 amarilla, Carta 2 verde)
-Vocero: 50 Partidas Ganadas, Actividad regular, Logros (Carta verde, y roja)
-Operador: 75 Partidas Ganadas, Actividad Buena en la sala, Logros (Carta dorada, Carta 5 roja)

**Comment by Slayer95** [comment]
Lo mismo que en https://github.com/Slayer95/Pandora-Showdown/issues/9.

Como le comentaba a @Sakuchii, he cambiado la finalidad de este repositorio.
Si tienes sugerencias para programar, postealas en https://bitbucket.org/Slayer95/pandora-issues/issues/2/implementar-logros
