### ISSUE TITLE
Sugerencia para ganar pd como los tours en la sala UNO !

### ISSUE THREAD

**Issue by Sakuchii** [Slayer95/Pandora-Showdown#12]
Bueno a mi punto de vista es que la sala UNO está un tanto abandonada y aburrida,solo revive cuando hay una importante cantidad de pd a juego. Se me ocurrió hace unas 
semanas que cada partida de uno de una considerable cantidad de pd como los tours y así que propiamente (como la sala 1vs1) tenga su partidario, y allí acaba mi idea, Gracias ^^

**Comment by Slayer95** [comment]
Hola, @Sakuchii , es buena idea y la implementaré en cuanto pueda.

Por cierto, he cambiado la finalidad de este repositorio. Si tienes otras sugerencias que creas que corresponde implementarlas en el código, postealas en https://bitbucket.org/Slayer95/pandora-issues
