### ISSUE TITLE
Hacer más APIs disponibles en Plugins.HTMLUtils

### ISSUE THREAD

**Issue by Slayer95** [Slayer95/Pandora-Showdown#14]
- ``Plugins.HTMLUtils.escape``
- ``Plugins.HTMLUtils.unescape``
- ``Plugins.HTMLUtils.sanitize``
- ``Plugins.HTMLUtils.linkify``

Si renombramos ``Plugins.HTMLUtils`` => ``Plugins.HTML``, resultaría natural usarlo como un "tag" para template strings, al estilo ``Plugins.HTML`hola ${planet}```
- ``Plugins.HTMLUtils``

**Comment by KevinF15** [comment]
Ok me pongo a trabajar en ellas :yum:

**Comment by KevinF15** [comment]
Añadidas: 
:white_check_mark:  ``Plugins.HTML.escape`` [(8a32c6f)](https://github.com/Slayer95/Pandora-Showdown/commit/8a32c6f556fdffb19637708ba84c20be05102e85#diff-2c0942bd263ee83ed8f66ed659396230R113)
:white_check_mark:  ``Plugins.HTML.escape`` [(8a32c6f)](https://github.com/Slayer95/Pandora-Showdown/commit/8a32c6f556fdffb19637708ba84c20be05102e85#diff-2c0942bd263ee83ed8f66ed659396230R118)

**Comment by Slayer95** [comment]
Yay. Buen trabajo hasta ahora, @KevinF15  :]

**Comment by Slayer95** [comment]
Resuelto en 50c8e47907c5d1a7, 8a32c6f556fdff y 11ef6bc6db06528d

**Comment by Slayer95** [comment]
Falta implementar la función de tag ``Plugins.HTML``
