### ISSUE TITLE
UNO: Logros

### ISSUE THREAD

**Issue by Darukia** [Slayer95/Pandora-Showdown#9]
Como bien dice el titulo, esta idea trata sobre los Logros que se obtengan realizar y jugar determinadas acciones, ganar eventos... Entre otros.
Para observar estos logros, se utilizaría un menú desplegable que muestre los logros actuales del usuario en cuestión, como el de las medallas de las ligas. Se conseguirían fácilmente dentro del juego, ya sea usando una carta un determinado de veces, ganando muchas partidas a la ves, etc etc..
Ejemplo: 
-Carta Reversa: La obtienes usando 4 veces en una partida la Carta Reversa.. 
-Carta Dorada: La obtienes participando y quedando en 1° Puesto en 3 UNO's seguidos.
-Carta Verde: La obtienes con 6 cartas verdes en el mazo.

**Comment by Darukia** [comment]
Otra idea que tuve trata básicamente sobre los Rangos de la sala "UNO Tower" que se obtengan mediante la actividad del usuario en ya dicha sala, sus partidas ganadas, y sus "Logros".(Tema anterior)
Para las partidas ganadas se utilizaría una especie de "Tourhof" (Cantidad de partidas ganadas).
Ejemplo:
-Destacado: 25 Partidas Ganadas, Actividad reciente en la sala, Logros (Carta 9 amarilla, Carta 2 verde)
-Vocero: 50 Partidas Ganadas, Actividad regular, Logros (Carta verde, y roja)
-Operador: 75 Partidas Ganadas, Actividad Buena en la sala, Logros (Carta dorada, Carta 5 roja)

**Comment by Slayer95** [comment]
Buena idea, pero requiere trabajo. Se seguirá el progreso en https://bitbucket.org/Slayer95/pandora-issues/issues/2/implementar-logros
